# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

name: TAS '24
author: Martin Porcheron
title: TAS '24
email: martin+taswebsite@porcheron.uk
lang: en-GB
description: >-
  The 2024 International Symposium on Trustworthy Autonomous Systems 
timezone: America/Chicago

conference:
  longname: Second International Symposium on Trustworthy Autonomous Systems
  shortname: TAS '24
  completename: Second International Symposium on Trustworthy Autonomous Systems (TAS '24)
  year: 2024
  location: Texas, United States
  dates: 'September 15-18, 2024'

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /blog/:year/:month/:day/:title/

repository: mixedrealitylab/tas-symposium
produrl: https://symposium.tas.ac.uk/2024

github:
  repo: https://github.com/mixedrealitylab/tas-symposium/
  link_title: "View edit on GitHub"

# Social settings
social:
    browser:
        theme_colour: '000066'
    twitter:
        username: tas_hub
        card: /assets/icn/twittercard.png
        card_alt: TAS '24 will take place at the University of Texas on XXXX

# Build settings
# plugins_dir: ./_plugins
plugins:
 - jekyll-menus
 - jekyll-datapage-generator
 - jekyll-titles-from-headings
#  - jekyll-github-metadata
#   - jekyll-feed
#   - jekyll-last-modified-at
#   - jekyll-minifier
#   - jekyll-optional-front-matter
#   - jekyll-redirect-from
#   - jekyll-sitemap
#  - jekyll-datapage-generator
#  - jekyll-target-blank

jekyll-last-commit:
  date_format: '%d-%b-%Y %R'       # default: `%B %d, %Y`
  should_fall_back_to_mtime: false # default: `true`
  data_files_key: 'meta'           # default: meta

liquid:
  error_mode: strict
  strict_variables: false
  strict_filters: true

# SASS generation
sass:
    style: compressed

# Title generation from headings
# titles_from_headings:
#     enabled: true
#     strip_title: true
#     collections: true

# Page generation from data
page_gen-dirs: true # uncomment, if you prefer to generate named folders
page_gen:
#    - data: prg_sessions
#      template: programme-ical
#      name: id
#      extension: ics
#      dir: '/programme/ics'
#      index_files: false
   - data: prg_sessions
     template: programme-redirect
     name: id
     dir: '/programme/link/'
     index_files: false

# Pagination
pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 5
  permalink: '/page/:num/'
  title: ':title (page :num/:max)'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'

# Exclude from minificartion
# jekyll-minifier:
#   compress_css: false
#   exclude: ['feed.xml', '*.ics', 'posters/*']

# Sitemap configutation
defaults:
  - scope:
      path:            ""
    values:
      layout:          "page"
  - scope:
      path:            ""
      type:            "posts" 
    values:
      layout:          "post"
  - scope:
      path:            "pubs/bibtex/*"
    values:
      sitemap:         false
  - scope:
      path:            "assets/**/*.pdf"
    values:
      sitemap:         false

# Excerpt separator
excerpt_separator: <!--more-->

# Minification
# jekyll-minifier:
#   uglifier_args:
#     harmony: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
